/**
 * Blank order used to seed the "New Order" form. Same shape as orderData.js
 * minus fulfilment and notes, which only apply once an order exists, plus
 * timeAtAddress which drives whether the previous address block shows.
 */
export const blankOrder = {
  account: {
    customerType: '',
    fullName: '',
    accountRef: '',
    accountNumber: '',
    dob: '',
    tektonLink: '',
  },
  contact: { mobile: '', landline: '', email: '' },
  billingAddress: { line1: '', line2: '', city: '', postcode: '' },
  previousAddress: { line1: '', line2: '', city: '', postcode: '' },
  deliveryAddress: { line1: '', line2: '', city: '', postcode: '' },
  timeAtAddress: '',
  currentPackage: { network: '', handset: '', spend: '', eligibilityDate: '' },
  saleDetails: {
    handsetOld: '',
    tariffOld: '',
    agentName: '',
    eligibilityDate: '',
    saleType: '',
    boxValue: '',
    simCard: '',
    quoteId: '',
    spendCap: '',
    contractTerm: '',
    contractEndTermDate: '',
  },
  additionalSale: {
    cashback: '',
    additionalFunding: '',
    pacCode: '',
    portingMobile: '',
    networkAccountNumber: '',
    businessConsumer: '',
    newNetwork: '',
    connectionDate: '',
    portDate: '',
  },
  handsetSelect: {
    catalogId: '',
    make: '',
    model: '',
    color: '',
    memory: '',
    price: '',
    supplier: '',
  },
  tariffType: {
    catalogId: '',
    code: '',
    price: '',
    minutes: '',
    texts: '',
    data: '',
    duration: '',
  },
  buyout: '',
  boltOns: '',
  specialRequirement: '',
  bankDetails: {
    accountName: '',
    accountNumber: '',
    sortCode: '',
    directDebitDueDate: '',
    bankName: '',
    bankBranch: '',
    timeWithBank: '',
    recurringCardPayment: false,
    inCreditControl: false,
  },
  creditChecks: [],
  welcomeCalls: {
    completeOrNotRequired: '',
    customerSpokenTo: false,
    portSet: '',
    spendCapAppliedTekton: false,
    spendCapAppliedV4: false,
    notificationsAppliedVos: false,
    customerPortalSet: false,
    billingExplained: false,
    dailyTraveller: false,
    spendCapDuplicated: false,
    dailyTravellerDuplicated: false,
    thirdPartyGranted: false,
    notificationsSet: false,
    previousBoltOnsApplied: false,
    thirdParty: false,
  },
};
