/**
 * Seed rows for the orders list. In a live CRM this comes from a paginated
 * orders API; kept as plain data so OrdersListPage only ever reads an array.
 *
 * statusTone keys into the `.ol-status--*` chip colors in orders-list.css.
 */
export const INITIAL_ORDERS = [
  {
    id: 1,
    saleType: 'Three Consumer',
    agentName: 'JamieEvans',
    campaign: 'Three Q3 Consumer Switch',
    mobileNumber: 'New number',
    businessName: 'Linda Holbrey',
    postCode: 'DN31 2QW',
    status: 'Awaiting Contact',
    statusTone: 'awaiting',
    boxValue: '£ 48',
    placedDate: '2026-08-03',
    placedTime: '02:14 PM',
    eligibilityDate: '2026-08-03',
  },
  {
    id: 2,
    saleType: 'Three New Connection',
    agentName: 'Luca',
    campaign: 'Three Q3 Consumer Switch',
    mobileNumber: '07938699291',
    businessName: 'Zoe Larkins',
    postCode: 'NR31 7AX',
    status: 'Declined',
    statusTone: 'declined',
    boxValue: '£ 200.8',
    placedDate: '2026-08-03',
    placedTime: '02:07 PM',
    eligibilityDate: '2026-08-03',
  },
  {
    id: 3,
    saleType: 'Three New Connection',
    agentName: 'JamieEvans',
    campaign: 'Three Q3 Consumer Switch',
    mobileNumber: '07346690335',
    businessName: 'Edward Jacey',
    postCode: 'IP25 6NX',
    status: 'Declined',
    statusTone: 'declined',
    boxValue: '£ 231.35',
    placedDate: '2026-08-03',
    placedTime: '02:02 PM',
    eligibilityDate: '2026-08-03',
  },
  {
    id: 4,
    saleType: 'Three New Connection',
    agentName: 'amiriqbal',
    campaign: 'Three Q3 Consumer Switch',
    mobileNumber: '07799413223',
    businessName: 'Hayley Acton',
    postCode: 'GU8 5JN',
    status: 'To Process',
    statusTone: 'process',
    boxValue: '£ 128.65',
    placedDate: '2026-08-03',
    placedTime: '01:48 PM',
    eligibilityDate: '',
  },
  {
    id: 5,
    saleType: 'O2 Consumer',
    agentName: 'Luke',
    campaign: 'O2 Upgrade Drive',
    mobileNumber: '07730035147',
    businessName: 'Mr Daniel Rix',
    postCode: 'RM17 5NS',
    status: 'Awaiting Contact',
    statusTone: 'awaiting',
    boxValue: '£ 96.58',
    placedDate: '2026-08-03',
    placedTime: '01:15 PM',
    eligibilityDate: '2026-08-03',
  },
  {
    id: 6,
    saleType: 'EE Consumer',
    agentName: 'Tess',
    campaign: 'EE Essential Push',
    mobileNumber: '07795366485',
    businessName: 'Edith Ashton 1 of 2',
    postCode: 'L35 5BE',
    status: 'Awaiting Contact',
    statusTone: 'awaiting',
    boxValue: '£ 245.16',
    placedDate: '2026-08-03',
    placedTime: '12:51 PM',
    eligibilityDate: '2026-08-01',
  },
  {
    id: 7,
    saleType: 'EE Consumer',
    agentName: 'Tess',
    campaign: 'EE Essential Push',
    mobileNumber: '07795366485',
    businessName: 'Edith Ashton 2 of 2',
    postCode: 'L35 5BE',
    status: 'Awaiting Contact',
    statusTone: 'awaiting',
    boxValue: '£ 245.16',
    placedDate: '2026-08-03',
    placedTime: '12:51 PM',
    eligibilityDate: '2026-08-01',
  },
  {
    id: 8,
    saleType: 'Three New Connection',
    agentName: 'Luca',
    campaign: 'Three Q3 Consumer Switch',
    mobileNumber: '07519458136',
    businessName: 'Jarmani Owen',
    postCode: 'SS0 7LN',
    status: 'To Process',
    statusTone: 'process',
    boxValue: '£ 210',
    placedDate: '2026-08-03',
    placedTime: '12:33 PM',
    eligibilityDate: '2026-08-03',
  },
  {
    id: 9,
    saleType: 'Three New Connection',
    agentName: 'marcoadaggio',
    campaign: 'Three Q3 Consumer Switch',
    mobileNumber: '07939595513',
    businessName: 'Patricia Bridge',
    postCode: 'PR3 3EL',
    status: 'To Process',
    statusTone: 'process',
    boxValue: '£ 224',
    placedDate: '2026-08-03',
    placedTime: '12:10 PM',
    eligibilityDate: '2026-08-03',
  },
  {
    id: 10,
    saleType: 'O2 Upgrade',
    agentName: 'Mike',
    campaign: 'O2 Upgrade Drive',
    mobileNumber: '07768962325',
    businessName: 'Mr Richard Freeman (2 of 2)',
    postCode: 'CM6 2NX',
    status: 'Awaiting Stock',
    statusTone: 'stock',
    boxValue: '£ 105.1',
    placedDate: '2026-08-03',
    placedTime: '11:52 AM',
    eligibilityDate: '2026-08-03',
  },
];

function distinctSorted(field) {
  return [...new Set(INITIAL_ORDERS.map((o) => o[field]))].sort();
}

/** Filter dropdown options, derived from the data so a selection always matches something. */
export const ASSIGNED_USER_OPTIONS = distinctSorted('agentName');
export const SALE_TYPE_FILTER_OPTIONS = distinctSorted('saleType');

/** Authored rather than derived — includes a campaign with no orders yet, same as a real CRM. */
export const CAMPAIGN_OPTIONS = [
  'Three Q3 Consumer Switch',
  'EE Essential Push',
  'O2 Upgrade Drive',
  'Summer Retention Offer',
];
